Bump membrane core version
membraneframework/membrane_video_compositor_plugin pull request #144
Opened 2023-11-24 10:59 UTC by WojciechBarczynski

2023-11-24 11:26 UTC, mat-hek requested changes

2023-11-24 11:26 UTC, mat-hek commented on mix.exs
> +      {:membrane_core, "~> 1.0.0"},
```suggestion
      {:membrane_core, "~> 1.0"},
```

2023-11-24 11:26 UTC, mat-hek commented on examples/mix.exs
> +      {:membrane_core, "~> 1.0.0"},
```suggestion
      {:membrane_core, "~> 1.0"},
```

2023-11-24 11:26 UTC, mat-hek commented on examples/lib/dynamic_outputs.exs
> +alias Membrane.VideoCompositor.Examples.DynamicOutputs.Pipeline, as: DynamicOutputsPipeline
Didn't notice that before, but these names can awaken Java PTSD. Let's rename `Membrane.VideoCompositor.Examples.DynamicOutputs.Pipeline` to `DynamicOutputs.Pipeline` or `DynamicOutputsPipeline` and don't alias at all

2023-11-24 11:29 UTC, mat-hek commented on examples/lib/dynamic_outputs.exs
> +alias Membrane.VideoCompositor.Examples.DynamicOutputs.Pipeline, as: DynamicOutputsPipeline
And you can move the contents of `dynamic_outputs/pipeline.ex` into this script, I don't see a benefit for having this split into multiple files

2023-11-24 13:55 UTC, WojciechBarczynski commented on examples/lib/dynamic_outputs.exs
> +defmodule DynamicOutputsPipeline do
Everything here is copy-pasted from deleted files

2023-11-24 15:04 UTC, mat-hek reviewed
ok, now you can move the .exs files out of the lib directory and fix readme https://github.com/membraneframework/membrane_video_compositor_plugin/tree/bump_membrane_core_version#examples and I think we can merge ;)

2023-11-27 10:11 UTC, mat-hek approved these changes

2023-11-27 11:51 UTC, merged