Simplify scene
membraneframework/membrane_video_compositor_plugin pull request #96
Opened 2023-03-02 00:09 UTC by WojciechBarczynski

2023-03-06 14:39 UTC, jerzywilczek requested changes

2023-03-06 14:52 UTC, WojciechBarczynski commented on lib/membrane/video_compositor/scene/layout.ex
> +  end
I like this idea overall, but it's hard to tell from this spec that `Layout` should be defined by `struct` and `inputs`, `resolution`, and optional fields are fields in that `struct`. What do you think about:
```elixir
@type definition_t :: struct()
@type t :: %{
  :inputs => inputs_t(),
  :resolution => resolution_t(),
  optional(any() => any())
}
```
?

2023-03-06 15:25 UTC, WojciechBarczynski commented on lib/membrane/video_compositor/examples/easy.ex
> +  @sixteen_tenths 16.0 / 9.0
Fixed :)

2023-03-07 09:24 UTC, jerzywilczek commented on lib/membrane/video_compositor/scene/layout.ex
> +  end
I don't really get how this is supposed to be used, you have to elaborate

2023-03-07 09:29 UTC, jerzywilczek commented on lib/membrane/video_compositor/scene/layout.ex
> +  end
What do users have to do with this solution to have dialyzer typecheck their own transformations?

2023-03-07 10:43 UTC, WojciechBarczynski commented on lib/membrane/video_compositor/examples/hard.ex
> +  # }
https://membraneframework.atlassian.net/browse/MS-431

2023-03-07 10:45 UTC, DominikWolek commented on lib/membrane/video_compositor/scene/layout.ex
> +  end
I think we should change how we deal with inputs to the version Bartek proposed, but I'd rather do that in the main PR

2023-03-07 10:58 UTC, DominikWolek approved these changes
I've got no concerns beside other converstions

2023-03-07 12:53 UTC, jerzywilczek requested changes
:cowboy_hat_face:

2023-03-07 12:53 UTC, jerzywilczek commented on lib/membrane/video_compositor/scene/layout.ex
> +  end
Now that you've implemented this the way I proposed, you should remove the `get_layout_enforce_keys/0` function

2023-03-07 12:53 UTC, jerzywilczek commented on lib/membrane/video_compositor/examples/mock/layouts/overlay.ex
> +  @enforce_keys [:overlay_spec] ++ Layout.get_layout_enforce_keys()
`Layout.get_layout_enforce_keys()` should also be removed from here.

2023-03-07 12:53 UTC, jerzywilczek commented on lib/membrane/video_compositor/examples/mock/layouts/merging.ex
> +  @enforce_keys Layout.get_layout_enforce_keys()
`Layout.get_layout_enforce_keys()` should also be removed from here.

2023-03-07 12:53 UTC, jerzywilczek commented on lib/membrane/video_compositor/examples/mock/layouts/grid.ex
> +  @enforce_keys [:videos_count] ++ Layout.get_layout_enforce_keys()
`Layout.get_layout_enforce_keys()` should also be removed from here.

2023-03-07 13:04 UTC, merged